name: Retrieve reddit subreddit data every 15 minutes

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '7,21,36,51 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch latest data
      run: |-
        access_token=$(curl -X POST -A "${{ secrets.REDDIT_USER_AGENT }}" \
                            -d "grant_type=password&username=${{ secrets.REDDIT_USERNAME }}&password=${{ secrets.REDDIT_PASSWORD }}" \
                            --user "${{ secrets.REDDIT_CLIENT_ID }}:${{ secrets.REDDIT_CLIENT_SECRET }}" \
                            https://www.reddit.com/api/v1/access_token | jq -r '.access_token')
        
        while IFS='' read -r LINE || [ -n "${LINE}" ]; do
          echo "Downloading ${LINE}"
          REPO="https://sharms:${{ secrets.ACCESS_TOKEN }}@github.com/sharms/reddit-${LINE}-data.git"
          curl -H "Authorization: bearer ${access_token}" -A "${{ secrets.REDDIT_USER_AGENT }}" https://oauth.reddit.com/r/${LINE}/about.json > ${LINE}-about.json
          curl -H "Authorization: bearer ${access_token}" -A "${{ secrets.REDDIT_USER_AGENT }}" https://oauth.reddit.com/r/${LINE}.json > ${LINE}-subreddit.json
          echo "Commiting data to reddit-${LINE}-data"
          (
            REPO="https://sharms:${{ secrets.ACCESS_TOKEN }}@github.com/sharms/reddit-${LINE}-data.git"
            git clone ${REPO}
            cd reddit-${LINE}-data
            git config user.name "Automated"
            git config user.email "actions@users.noreply.github.com"
            cp ../${LINE}-about.json about.json
            cp ../${LINE}-subreddit.json subreddit.json
            git add -A
            timestamp=$(date -u)
            git commit -m "Latest data: ${timestamp}" || exit 0
            git push
          )&
        done < ./subreddits

        wait
