name: Import data every 15 minutes

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '7,21,36,51 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-20.04
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch reddit data
      run: |-
        access_token=$(curl -X POST -A "${{ secrets.REDDIT_USER_AGENT }}" \
                            -d "grant_type=password&username=${{ secrets.REDDIT_USERNAME }}&password=${{ secrets.REDDIT_PASSWORD }}" \
                            --user "${{ secrets.REDDIT_CLIENT_ID }}:${{ secrets.REDDIT_CLIENT_SECRET }}" \
                            https://www.reddit.com/api/v1/access_token | jq -r '.access_token')
        
        while IFS='' read -r LINE || [ -n "${LINE}" ]; do
          echo "Downloading ${LINE}"
          REPO="https://sharms:${{ secrets.ACCESS_TOKEN }}@github.com/sharms/reddit-${LINE}-data.git"
          curl -H "Authorization: bearer ${access_token}" -A "${{ secrets.REDDIT_USER_AGENT }}" https://oauth.reddit.com/r/${LINE}/about.json \
          | jq '{title: .data.title, active_user_count: .data.active_user_count, subscribers: .data.subscribers, public_description: .data.public_description, description: .data.description, allow_videos: .data.allow_videos}' \
          > ${LINE}-about.json
          curl -H "Authorization: bearer ${access_token}" -A "${{ secrets.REDDIT_USER_AGENT }}" https://oauth.reddit.com/r/${LINE}.json \
          | jq '.data.children | .[] | {title: .data.title, score: .data.score, upvote_ratio: .data.upvote_ratio, created: .data.created, url: .data.url, author: .data.author, is_video: .data.is_video, num_comments: .data.num_comments}' \
          > ${LINE}-subreddit.json
          echo "Commiting data to reddit-${LINE}-data"
          (
            REPO="https://sharms:${{ secrets.ACCESS_TOKEN }}@github.com/sharms/reddit-${LINE}-data.git"
            git clone ${REPO}
            cd reddit-${LINE}-data
            git config user.name "Automated"
            git config user.email "actions@users.noreply.github.com"
            cp ../${LINE}-about.json about.json
            cp ../${LINE}-subreddit.json subreddit.json
            git add -A
            timestamp=$(date -u)
            git commit -m "Latest data: ${timestamp}" || exit 0
            git push
          )&
        sleep 1
        done < ./subreddits

        wait
    - name: Fetch hackernews data
      run: |-
        REPO="https://sharms:${{ secrets.ACCESS_TOKEN }}@github.com/sharms/hackernews-topstories-data.git"
        git clone ${REPO}
        cd hackernews-topstories-data
        curl 'https://hacker-news.firebaseio.com/v0/topstories.json' -o topstories.json
        jq -j '.[] | "https://hacker-news.firebaseio.com/v0/item/",.,".json\n"' topstories.json | head -n50 \
        | xargs curl --parallel-max 5 | jq -s > items.json
        jq -j '.[] | select(.kids != null) | .kids[] | "https://hacker-news.firebaseio.com/v0/item/",.,".json\n"' items.json \
        | xargs curl --parallel-max 5 | jq -s > comments.json
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
